# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AqCsdvhbXdiM5-FjEZhuJdSL7WzqjeLr
"""

import os
os.makedirs('checkpoints', exist_ok=True)

import kagglehub
path = kagglehub.dataset_download("zaryabahmadkhan/2d-slicing-of-imagetbad-dataset")
path

# Commented out IPython magic to ensure Python compatibility.
import sys
import os
from google.colab import drive
drive.mount('/content/drive')
# %env CLEARML_WEB_HOST=https://app.clear.ml/
# %env CLEARML_API_HOST=https://api.clear.ml
# %env CLEARML_FILES_HOST=https://files.clear.ml
# %env CLEARML_API_ACCESS_KEY=XGMS61QRIXH7G4URU0X7VGTDAIQUVE
# %env CLEARML_API_SECRET_KEY=3mpOB_Br37BLBntBoUvtxmfbBfmkbkdfRUYGje8GfL1gwe_ufJd1w4UzuQWOPaAtTWE
project_path = '/content/drive/MyDrive/segmentation_project'
sys.path.append(project_path)
!pip install -q pytorch-lightning torchmetrics clearml hydra-core omegaconf
from modules.train import train

if __name__ == '__main__':
    model, trainer = train()

